# Generated by Django 6.1 on 2026-10-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_patient'),
        ('doctors', '0002_doctorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor', verbose_name='Bác sĩ'),
        ),
    ]
